applications:
  frontend:
    enabled: true
    replicaCount: 1
    image:
      repository: 814636798023.dkr.ecr.us-east-1.amazonaws.com/frontend
      tag: latest
    containerPort: 80
    service:
      port: 80
      type: NodePort

  backend:
    enabled: true
    replicaCount: 1
    image:
      repository: 814636798023.dkr.ecr.us-east-1.amazonaws.com/backend
      tag: latest
    containerPort: 5000
    service:
      port: 5000
      type: ClusterIP

database:
  host: "ecommerce.ccx0y0aq40h4.us-east-1.rds.amazonaws.com"
  name: ecommerce
  user: "admin"
  password: "mysecurepassword"

ingress:
  enabled: true

  className: alb

  scheme: internet-facing

  targetType: ip


