{{- range $name,$app := .Values.applications }}

apiVersion: apps/v1

kind: Deployment

metadata:

  name: {{ $name }}

spec:

  replicas:

    {{ $app.replicaCount }}

  selector:

    matchLabels:

      app: {{ $name }}

  template:

    metadata:

      labels:

        app: {{ $name }}

    spec:

      containers:

      - name: {{ $name }}

        image:

          "{{ $app.image.repository }}:{{ $app.image.tag }}"

        ports:

        - containerPort:

            {{ $app.containerPort }}

        envFrom:

        - configMapRef:

            name:

              {{ $name }}-config

        {{ if eq $name "backend" }}

        - secretRef:

            name:

              backend-secret

        {{ end }}

---

{{ end }}