{{- range $name,$app,$type := .Values.applications }}

apiVersion: v1

kind: Service

metadata:

  name:

    {{ $name }}-service

spec:

  selector:

    app:

      {{ $name }}

  ports:

  - port:

      {{ $app.service.port }}

    targetPort:

      {{ $app.containerPort }}

  type:

    {{ $type }}

---

{{ end }}
